theme: jekyll-theme-slate
collections:
  questions:
    output: true
    permalink: /questions/:path/
defaults:
  - scope:
      path: ''
      type: 'questions'
    values:
      layout: 'questions'
plugins:
  - jekyll-sitemap
