theme: jekyll-theme-slate
url: https://doplgangr.github.io
baseurl: /databasescraper
page_gen:
  - data: 'questions'
    template: 'questions'
    name: 'QUESTION_CODE'
    dir: 'question'
plugins:
  - jekyll-sitemap
